---
# - name: sample book
#   hosts: docker_client
#   tasks:
#     - copy:
#         src: "master.gitconfig"
#         dest: "~/.gitconfig"

- name: mandatory installations
  hosts: docker_client
  tasks:
    - apt:
        update_cache: yes
        name: bat
        state: latest
    - apt:
        update_cache: yes
        name: jq
        state: latest

